create table person_setting
(
    id        bigint generated by default as identity primary key,
    person_id numeric(40)  not null
        constraint fk_person_setting_on_person
            references postgres.public.person
            on update cascade on delete cascade,
    setting   varchar(255) not null,
    value     varchar(255) not null,
    unique (person_id, setting)
)