CREATE TABLE invitation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id         BIGINT                                  NOT NULL,
    invitation_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_invitation PRIMARY KEY (id)
);

ALTER TABLE invitation
    ADD CONSTRAINT uc_invitation_invitationcode UNIQUE (invitation_code);